name: Build Portable RetroArch for Miyoo Flip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up Docker's cross-platform build tools first
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Dynamically create the Dockerfile and then build the image
      - name: Create Dockerfile and Build Environment
        run: |
          cat <<'EOF' > Dockerfile
          # Use Debian Buster for ARM64 as the base image
          FROM arm64v8/debian:buster

          # Set environment variables
          ENV DEBIAN_FRONTEND=noninteractive

          # ==============================================================================
          # SECTION 1: INSTALL ALL SYSTEM DEPENDENCIES
          # ==============================================================================
          RUN apt-get update && \
              apt-get install -y --no-install-recommends \
                  build-essential \
                  git \
                  wget \
                  python3 \
                  python3-pip \
                  ninja-build \
                  pkg-config \
                  libudev-dev \
                  libdrm-dev \
                  libegl1-mesa-dev \
                  libgles2-mesa-dev \
                  libgl1-mesa-dev \
                  libasound2-dev \
                  libgbm-dev \
                  zlib1g-dev \
                  libpng-dev \
                  libsdl2-dev && \
              # Create a symlink for the DRM headers, which RetroArch expects
              ln -s /usr/include/libdrm /usr/include/drm && \
              # Clean up apt cache
              apt-get clean && rm -rf /var/lib/apt/lists/*

          # ==============================================================================
          # SECTION 2: MANUALLY INSTALL MODERN BUILD TOOLS
          # ==============================================================================

          # Manually install a modern version of CMake, required for SDL2
          RUN cd /tmp && \
              wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-aarch64.sh && \
              chmod +x cmake-3.26.4-linux-aarch64.sh && \
              ./cmake-3.26.4-linux-aarch64.sh --skip-license --prefix=/usr/local && \
              rm -f cmake-3.26.4-linux-aarch64.sh

          # Manually install a recent version of Meson
          RUN pip3 install --upgrade meson

          # ==============================================================================
          # SECTION 3: MANUALLY BUILD AND INSTALL REQUIRED LIBRARIES
          # ==============================================================================

          # Manually build and install SDL2 with specific features for our device
          RUN cd /tmp && \
              git clone --depth=1 https://github.com/libsdl-org/SDL.git && \
              cd SDL && \
              mkdir build && cd build && \
              cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DSDL_STATIC=OFF -DSDL_VIDEO_WAYLAND=OFF -DSDL_VIDEO_X11=OFF -DSDL_VIDEO_KMSDRM=ON && \
              make -j4 && \
              make install && \
              ldconfig && \
              cd / && rm -rf /tmp/SDL

          # ==============================================================================
          # SECTION 4: BUILD RETROARCH V1.21.0 AND PREPARE OUTPUT
          # ==============================================================================

          # Clone the full repo, checkout the specific v1.21.0 tag, and build RetroArch
          RUN cd /tmp && \
              git clone https://github.com/libretro/RetroArch.git && \
              cd RetroArch && \
              git checkout v1.21.0 && \
              export CFLAGS="-O2 -pipe -s" && \
              export LDFLAGS="-s" && \
              ./configure \
                --enable-kms \
                --enable-egl \
                --enable-opengles \
                --enable-udev \
                --enable-alsa \
                --disable-x11 \
                --disable-wayland && \
              make -j4

          # Create a clean, portable output directory structure
          RUN mkdir -p /build_output/RetroArch/.retroarch/cores && \
              mkdir -p /build_output/RetroArch/.retroarch/saves && \
              mkdir -p /build_output/RetroArch/.retroarch/states && \
              mkdir -p /build_output/RetroArch/.retroarch/system && \
              # Copy the compiled binary and the config file into the main folder
              cp /tmp/RetroArch/retroarch /build_output/RetroArch/ && \
              cp /tmp/RetroArch/retroarch.cfg /build_output/RetroArch/ && \
              # Use sed to automatically update the default paths in the config file
              sed -i 's/^#\s*core_assets_directory.*$/core_assets_directory = ".\/.retroarch\/assets"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*core_directory.*$/core_directory = ".\/.retroarch\/cores"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*savefile_directory.*$/savefile_directory = ".\/.retroarch\/saves"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*savestate_directory.*$/savestate_directory = ".\/.retroarch\/states"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*system_directory.*$/system_directory = ".\/.retroarch\/system"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*overlay_directory.*$/overlay_directory = ".\/.retroarch\/overlays"/' /build_output/RetroArch/retroarch.cfg
          EOF

          # Now, build the Docker image from the file we just created
          docker build -t my-build-env .

      # Extract the final portable folder from the image
      - name: Extract Portable RetroArch Folder
        run: |
          mkdir -p artifacts
          docker create --name temp_container my-build-env
          docker cp temp_container:/build_output/RetroArch/. artifacts/
          docker rm temp_container

      # Upload the final folder as a downloadable artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RetroArch_Portable_v1.21.0
          path: artifacts/
