name: Build RetroArch for TrimUI Smart Pro (Brick)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # STEP 1: PIN THE RUNNER TO A STABLE LTS VERSION
    runs-on: ubuntu-22.04

    steps:
    # ==========================================================================
    # 2. Set up a Multi-Arch build environment for Ubuntu 22.04 (Jammy)
    # ==========================================================================
    - name: Setup Multi-Arch Environment
      run: |
        # Add the arm64 architecture
        sudo dpkg --add-architecture arm64
        
        # Add the official "ports" repository for arm64 packages for Ubuntu 22.04 (Jammy)
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/arm64.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/arm64.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/arm64.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/arm64.list
        
        # Now, update the package list
        sudo apt-get update

    # ==========================================================================
    # 3. Download the Official Arm Compiler Toolchain
    # ==========================================================================
    - name: Download and Setup Arm GNU Toolchain
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        mkdir -p ${{ github.workspace }}/arm-toolchain
        tar -xf arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz -C ${{ github.workspace }}/arm-toolchain --strip-components=1
        echo "${{ github.workspace }}/arm-toolchain/bin" >> $GITHUB_PATH

    # ==========================================================================
    # 4. Install Host and Target (arm64) Dependencies
    # ==========================================================================
    - name: Install Host and Target Dependencies
      run: |
        sudo apt-get install -y build-essential pkg-config git
        sudo apt-get install -y libegl-dev:arm64 libgles2-mesa-dev:arm64 libudev-dev:arm64 libasound2-dev:arm64 libgbm-dev:arm64

    # ==========================================================================
    # 5. Clone and Configure RetroArch for Cross-Compilation
    # ==========================================================================
    - name: Clone and Configure RetroArch v1.21.0
      run: |
        git clone https://github.com/libretro/RetroArch.git
        cd RetroArch
        git checkout v1.21.0
        
        export CC=aarch64-none-linux-gnu-gcc
        export CXX=aarch64-none-linux-gnu-g++
        export AR=aarch64-none-linux-gnu-ar
        export STRIP=aarch64-none-linux-gnu-strip
        export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
        export CFLAGS="-I/usr/include/aarch64-linux-gnu"
        export LDFLAGS="-L/usr/lib/aarch64-linux-gnu"

        ./configure \
          --host=aarch64-none-linux-gnu \
          --disable-x11 --disable-wayland --disable-pulse \
          --enable-opengles --enable-egl --enable-kms

    # ==========================================================================
    # 6. Compile RetroArch
    # ==========================================================================
    - name: Compile RetroArch
      run: |
        cd RetroArch
        make -j$(nproc)

    # ==========================================================================
    # 7. Upload the finished RetroArch binary as an artifact
    # ==========================================================================
    - name: Upload RetroArch Binary
      uses: actions/upload-artifact@v4
      with:
        name: retroarch-trimui-brick
        path: RetroArch/retroarch
