name: Build Portable RetroArch (Final Attempt)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Dockerfile and Build Environment
        run: |
          cat <<'EOF' > Dockerfile
          # Use Debian Buster for ARM64 as the base image
          FROM arm64v8/debian:buster

          # Set environment variables
          ENV DEBIAN_FRONTEND=noninteractive CMAKE_VERSION=3.26.4

          # Install all system dependencies
          RUN apt-get update && \
              apt-get install -y --no-install-recommends \
                  build-essential \
                  git \
                  wget \
                  python3 \
                  python3-pip \
                  ninja-build \
                  pkg-config \
                  libudev-dev \
                  libdrm-dev \
                  libegl1-mesa-dev \
                  libgles2-mesa-dev \
                  libgl1-mesa-dev \
                  libasound2-dev \
                  libgbm-dev \
                  zlib1g-dev \
                  libpng-dev \
                  libsdl2-dev && \
              ln -s /usr/include/libdrm /usr/include/drm && \
              apt-get clean && rm -rf /var/lib/apt/lists/*

          # Manually install a modern version of CMake
          RUN cd /tmp && \
              wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-<span class="math-inline">\{CMAKE\_VERSION\}\-linux\-aarch64\.sh && \\
chmod \+x cmake\-</span>{CMAKE_VERSION}-linux-aarch64.sh && \
              ./cmake-<span class="math-inline">\{CMAKE\_VERSION\}\-linux\-aarch64\.sh \-\-skip\-license \-\-prefix\=/usr/local && \\
rm \-f cmake\-</span>{CMAKE_VERSION}-linux-aarch64.sh

          # Manually build and install SDL2
          RUN cd /tmp && \
              git clone --depth=1 https://github.com/libsdl-org/SDL.git && \
              cd SDL && \
              mkdir build && cd build && \
              cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DSDL_STATIC=OFF -DSDL_VIDEO_WAYLAND=OFF -DSDL_VIDEO_X11=OFF -DSDL_VIDEO_KMSDRM=ON && \
              make -j4 && \
              make install && \
              ldconfig && \
              cd / && rm -rf /tmp/SDL

          # Build RetroArch v1.21.0
          RUN cd /tmp && \
              git clone https://github.com/libretro/RetroArch.git && \
              cd RetroArch && \
              git checkout v1.21.0 && \
              # Using more generic compiler flags for better portability
              export CFLAGS="-O2 -pipe" && \
              ./configure \
                --enable-kms \
                --enable-egl \
                --enable-opengles \
                --enable-udev \
                --enable-alsa \
                --disable-x11 \
                --disable-wayland && \
              make -j4

          # Create a clean, portable output directory structure
          RUN mkdir -p /build_output/RetroArch/.retroarch/cores && \
              mkdir -p /build_output/RetroArch/.retroarch/saves && \
              mkdir -p /build_output/RetroArch/.retroarch/states && \
              mkdir -p /build_output/RetroArch/.retroarch/system && \
              cp /tmp/RetroArch/retroarch /build_output/RetroArch/ && \
              cp /tmp/RetroArch/retroarch.cfg /build_output/RetroArch/ && \
              sed -i 's/^#\s*core_assets_directory.*<span class="math-inline">/core\_assets\_directory \= "\.\\/\.retroarch\\/assets"/' /build\_output/RetroArch/retroarch\.cfg && \\
sed \-i 's/^\#\\s\*core\_directory\.\*</span>/core_directory = ".\/.retroarch\/cores"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*savefile_directory.*<span class="math-inline">/savefile\_directory \= "\.\\/\.retroarch\\/saves"/' /build\_output/RetroArch/retroarch\.cfg && \\
sed \-i 's/^\#\\s\*savestate\_directory\.\*</span>/savestate_directory = ".\/.retroarch\/states"/' /build_output/RetroArch/retroarch.cfg && \
              sed -i 's/^#\s*
