name: Build RetroArch for TrimUI Smart Pro (Brick)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ==========================================================================
    # 1. Set up a Multi-Arch build environment
    # ==========================================================================
    - name: Setup Multi-Arch Environment
      run: |
        # Add the arm64 architecture to the runner's package manager
        sudo dpkg --add-architecture arm64
        sudo apt-get update

    # ==========================================================================
    # 2. Download the Official Arm Compiler Toolchain
    # ==========================================================================
    - name: Download and Setup Arm GNU Toolchain
      run: |
        echo "Downloading official Arm GNU Toolchain..."
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        mkdir -p ${{ github.workspace }}/arm-toolchain
        tar -xf arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz -C ${{ github.workspace }}/arm-toolchain --strip-components=1
        echo "${{ github.workspace }}/arm-toolchain/bin" >> $GITHUB_PATH

    # ==========================================================================
    # 3. Install Host and Target (arm64) Dependencies
    # ==========================================================================
    - name: Install Host and Target Dependencies
      run: |
        # Install build tools for the runner (host)
        sudo apt-get install -y build-essential pkg-config git
        # Install the required libraries for the target device (arm64)
        sudo apt-get install -y libegl-dev:arm64 libgles2-mesa-dev:arm64 libudev-dev:arm64 libasound2-dev:arm64 libgbm-dev:arm64

    # ==========================================================================
    # 4. Clone and Configure RetroArch for Cross-Compilation
    # ==========================================================================
    - name: Clone and Configure RetroArch v1.21.0
      run: |
        git clone https://github.com/libretro/RetroArch.git
        cd RetroArch
        git checkout v1.21.0
        
        echo "Configuring RetroArch for cross-compilation..."
        # Set environment variables to point the compiler to the correct libraries and headers
        export CC=aarch64-none-linux-gnu-gcc
        export CXX=aarch64-none-linux-gnu-g++
        export AR=aarch64-none-linux-gnu-ar
        export STRIP=aarch64-none-linux-gnu-strip
        export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
        export CFLAGS="-I/usr/include/aarch64-linux-gnu"
        export LDFLAGS="-L/usr/lib/aarch64-linux-gnu"

        ./configure \
          --host=aarch64-none-linux-gnu \
          --disable-x11 --disable-wayland --disable-pulse \
          --enable-opengles --enable-egl --enable-kms

    # ==========================================================================
    # 5. Compile RetroArch
    # ==========================================================================
    - name: Compile RetroArch
      run: |
        cd RetroArch
        make -j$(nproc)

    # ==========================================================================
    # 6. Upload the finished RetroArch binary as an artifact
    # ==========================================================================
    - name: Upload RetroArch Binary
      uses: actions/upload-artifact@v4
      with:
        name: retroarch-trimui-brick
        path: RetroArch/retroarch
