name: Build RetroArch for TrimUI Smart Pro (Brick) - Docker Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build RetroArch inside an arm64 Container and Extract Binary
      run: |
        # Dynamically create our Dockerfile. This defines the perfect build environment.
        cat <<EOF > Dockerfile
        # Start from a clean, arm64 Ubuntu 22.04 image
        FROM arm64v8/ubuntu:22.04

        # Avoid interactive prompts during package installation
        ENV DEBIAN_FRONTEND=noninteractive

        # Install every possible dependency RetroArch might need, natively for arm64
        RUN apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            git \
            ca-certificates \
            wget \
            pkg-config \
            libegl-dev \
            libgles2-mesa-dev \
            libudev-dev \
            libasound2-dev \
            libgbm-dev \
            libsystemd-dev \
            libdrm-dev \
            libxkbcommon-dev \
            libfreetype6-dev \
            libgl1-mesa-dev \
            zlib1g-dev

        # Set a working directory inside the container
        WORKDIR /build

        # Clone and configure RetroArch
        RUN git clone https://github.com/libretro/RetroArch.git && \
            cd RetroArch && \
            git checkout v1.21.0 && \
            ./configure \
              --enable-opengles \
              --enable-egl \
              --enable-kms \
              --enable-freetype \
              --disable-x11 \
              --disable-wayland \
              --disable-pulse && \
            make -j\$(nproc)
        EOF

        # Use Docker to build the image. The --output flag tells Docker to
        # copy the build result to a local 'output' directory instead of saving the image.
        docker buildx build \
          --platform linux/arm64 \
          --output type=local,dest=./output \
          .

    - name: Upload the final RetroArch binary
      uses: actions/upload-artifact@v4
      with:
        name: retroarch-trimui-brick
        path: output/build/RetroArch/retroarch
